#!/usr/bin/env zsh
#source "${HOME}/.cargo/env"
#export PATH="${HOME}/.cargo/bin:${PATH}"

# don't bother making electrs.core files
ulimit -c

# get credentials from bitcoin.conf directly
BITCOIN_RPC_USER=$(grep 'rpcuser=' ${HOME}/bitcoin.conf|cut -d = -f2|head -1)
BITCOIN_RPC_PASS=$(grep 'rpcpassword=' ${HOME}/bitcoin.conf|cut -d = -f2|head -1)

# run in loop in case of crash
until false
do
	cd "${HOME}/electrs"
	cargo run \
		--release \
		--bin electrs \
		-- \
		--network testnet \
		--http-socket-file "${HOME}/socket/esplora-bitcoin-testnet" \
		--daemon-dir "${HOME}" \
		--db-dir "/electrs" \
		--cookie "${BITCOIN_RPC_USER}:${BITCOIN_RPC_PASS}" \
		--cors '*' \
		--address-search \
		-vvv
	sleep 1
done
