on:
  pull_request:
  push:
    branches:
      - mempool


name: Compile Check and Lint

jobs:
  check:
    name: Compile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@1.70
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo check --all-features

  fmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@1.70
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@1.70
      - name: Cache dependencies
        uses: actions/cache@v3
        with: # test cache key is different (adding test cfg is a re-compile)
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --package electrs --lib --all-features

  clippy:
    name: Linter
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      matrix: # Try all combinations of features. Some times weird things appear.
        features: [
          '',
          '-F electrum-discovery',
          '-F liquid',
          '-F electrum-discovery,liquid',
        ]
    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@1.70
        with:
          components: clippy
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Clippy with Features = ${{ matrix.features }}
        run: cargo clippy ${{ matrix.features }} -- -D warnings
